### ISSUE TITLE
Timestamp

### ISSUE THREAD

**Issue by KaKi87** [predbdotovh/website#1]
Hi,

How do we parse the "preAt" timestamp ?

I tried `new Date(rows[i].preAt)` but it's 1970, so I guess this is not a Unix UTC date...

Could you help me please ?

Thanks.

**Comment by predbdotovh** [comment]
Not sure if you managed to find an answer, but just in case :
`preAt` is a classic unix timestamp, while javascript `new Date()` expects a milisecond based unix timestamp.

So the proper way for your code would be `new Date(rows[i].preAt * 1000)`
